# Generated by Django 5.2.14 on 2026-06-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_class_name_profile_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='class_name',
            new_name='academic_class',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='semester_number',
        ),
    ]
