# Generated by Django 5.2.14 on 2026-06-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_attendancesession_attendancerecord_timetable_and_more'),
        ('users', '0003_rename_class_name_profile_academic_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.department'),
        ),
    ]
