# Generated by Django 5.2.14 on 2026-06-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_eventcoordinator'),
        ('users', '0004_profile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remark', models.TextField(blank=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.academicclass')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.department')),
            ],
        ),
    ]
