from django.urls import path
from . import views

urlpatterns = [
    path("student/notices/", views.student_notices, name="student_notices"),
    path("student/events/", views.student_events, name="student_events"),
    path("event/<int:event_id>/", views.event_detail, name="event_detail"),
    path('student/attendance/', views.student_attendance, name='student_attendance'),
    path('student/attendance/<int:subject_id>/', views.student_attendance_detail, name='student_attendance_detail'),
    path('student/subjects/', views.student_subjects, name="student_subjects"),
    path('student/timetable/', views.student_timetable, name="student_timetable"),
    path("student/coordinator-events/", views.student_coordinator_events, name="student_coordinator_events"),
    path("student/past-coordinator-events/", views.student_past_coordinator_events, name="student_past_coordinator_events"),
    path("subjects/", views.faculty_subjects, name="faculty_subjects"),
    path("notices/", views.faculty_notices, name="faculty_notices"),
    path("notices/create/", views.create_notice, name="create_notice"),
    path("notices/<int:notice_id>/", views.notice_detail, name="notice_detail"),
    path("notices/<int:notice_id>/edit/", views.edit_notice, name="edit_notice"),
    path("notices/<int:notice_id>/delete/", views.delete_notice, name="delete_notice"),
    path("events/", views.faculty_events, name="faculty_events"),
    path("events/create/", views.create_event, name="create_event"),
    path("events/faculty-only/", views.faculty_events_only, name="faculty_events_only"),
    path("events/<int:event_id>/edit/", views.edit_event, name="edit_event"),
    path("events/<int:event_id>/delete/", views.delete_event, name="delete_event"),
    path("events/<int:event_id>/assign-coordinators/", views.assign_event_coordinators, name="assign_event_coordinators"),
    path("timetable/", views.faculty_timetable, name="faculty_timetable"),
    path("attendance/mark/", views.mark_attendance, name="mark_attendance"),
    path("attendance/view/", views.faculty_view_attendance, name="faculty_view_attendance"),
    path("attendance/report/", views.faculty_attendance_report, name="faculty_attendance_report"),
    path("attendance/request-correction/", views.request_attendance_correction, name="request_attendance_correction"),
]
