"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cs4-v#di+1czlhkadc&b(#otutwxjxd%r_(0l8)qu8j%vgo=2i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = ['.vercel.app', 'localhost', '127.0.0.1']
# Add CSRF trusted origins for Vercel
CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']

# Secret code for registering as an Administrator on the web onboarding page
ADMIN_SIGNUP_SECRET = os.environ.get('ADMIN_SIGNUP_SECRET', 'CampusOneAdmin2026')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'users',
    'academics',
    'assignments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.ProfileCreationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Switch to Vercel/Neon Postgres in production (when VERCEL env is set to 1 and POSTGRES_URL is available)
if os.environ.get('VERCEL') == '1' and os.environ.get('POSTGRES_URL'):
    DATABASES['default'] = dj_database_url.config(
        default=os.environ.get('POSTGRES_URL'),
        conn_max_age=600,
        ssl_require=True
    )
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS= [ BASE_DIR / 'static',]
# Directory where collectstatic will compile static files during build
STATIC_ROOT= BASE_DIR/'staticfiles'
# Enable compression and caching of static assets
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "/media/"

if os.environ.get('VERCEL') == '1':
    bucket_name = os.environ.get("SUPABASE_STORAGE_BUCKET", "media")
    endpoint_url = os.environ.get("SUPABASE_S3_ENDPOINT", "")
    if "supabase.co" in endpoint_url:
        try:
            project_ref = endpoint_url.split("//")[1].split(".")[0]
            custom_domain = f"{project_ref}.supabase.co/storage/v1/object/public/{bucket_name}"
        except Exception:
            custom_domain = None
    else:
        custom_domain = None

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.environ.get("SUPABASE_ACCESS_KEY_ID"),
                "secret_key": os.environ.get("SUPABASE_SECRET_ACCESS_KEY"),
                "bucket_name": bucket_name,
                "endpoint_url": endpoint_url,
                "custom_domain": custom_domain,
                "default_acl": None,
                "querystring_auth": False,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
else:
    MEDIA_ROOT = BASE_DIR / "media"

# Email Configuration
'''if DEBUG:
    # Use console backend for development/testing
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:'''
    # Use live SMTP backend in production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'campusone00@gmail.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')


DEFAULT_FROM_EMAIL = 'CampusOne <campusone00@gmail.com>'

#DEFAULT_FROM_EMAIL = 'noreply@campusone.com'