# Generated by Django 5.2.14 on 2026-06-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='AcademicClass',
        ),
    ]
