# Generated by Django 5.2.14 on 2026-06-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_class_academicclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicclass',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.department'),
        ),
        migrations.AlterField(
            model_name='academicclass',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.semester'),
        ),
    ]
