# Generated by Django 5.2.14 on 2026-06-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicclass_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicclass')),
            ],
        ),
    ]
