# Generated by Django 5.2.14 on 2026-06-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_facultysubject'),
        ('users', '0003_rename_class_name_profile_academic_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile')),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.attendancesession')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('faculty_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.facultysubject')),
            ],
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.timetable'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('timetable', 'lecture_date')},
        ),
    ]
