# Generated by Django 5.2.14 on 2026-06-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_attendancesession_attendancerecord_timetable_and_more'),
        ('users', '0004_profile_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('attendance_session', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'academic_class')},
        ),
    ]
