# Generated by Django 5.2.14 on 2026-06-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_attendancecorrectionrequest'),
        ('users', '0004_profile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('notice_type', models.CharField(choices=[('GENERAL', 'General'), ('DEPARTMENT', 'Department'), ('CLASS', 'Class')], max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicclass')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.department')),
            ],
        ),
    ]
