# Generated by Django 5.2.14 on 2026-06-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.academicclass'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.department'),
        ),
    ]
