# Generated by Django 5.2.14 on 2026-06-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_event'),
        ('users', '0004_profile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile')),
            ],
            options={
                'unique_together': {('event', 'student')},
            },
        ),
    ]
